### ISSUE TITLE
Failed to add song to queue: parsing JSON failed

### ISSUE THREAD

**Issue by GolDNenex** [jontze/cadency-rs#90] opened 2023-02-22 23:37 UTC
Hi,

Each time i try to use '/Play Hey Jude Beatles' (or with a link), the command failed. My output look like this:

```
[2023-02-22T23:25:18Z INFO  cadency_core::handler::command] 🚀 Start Cadency Discord Bot

[2023-02-22T23:25:18Z INFO  cadency_core::handler::command] ⏳ Started to submit commands, please wait... 

[2023-02-22T23:25:48Z INFO  cadency_core::handler::command] ⚡ Execute 'play' command

[2023-02-22T23:25:48Z DEBUG cadency_core::utils::voice] Try to join guild with id: GuildId(96636873966903296) 

[2023-02-22T23:25:49Z DEBUG cadency_core::utils::voice] Add song to playlist: 'synthwave'

[2023-02-22T23:25:53Z ERROR cadency_commands::play] ❌ Failed to add song to queue: parsing JSON failed

[2023-02-22T23:25:53Z ERROR cadency_core::handler::command] ❌ Command execution failed: Command { message: ":x: **Couldn't add audio source to the queue!**" }

[2023-02-22T23:25:59Z INFO  cadency_core::handler::command] ✅ Application commands submitted
 
```

**Comment by jontze** [comment] 2023-02-22 23:57
Hey @GolDNenex 
The First thing I recognized by looking at the logs, is that the play command is received before all commands are submitted and registered to the discord api.

The bot is ready to receive commands after the green check appears in the logs (Application commands submitted).

Also be aware that if you start the bot for the first time, it might take some time (~15 mins) until the commands actual work. This is AFAIK due to caching on the side of Discord.

Is the problem still present if you wait a few mins before submitting the first command?

**Comment by jontze** [comment] 2023-02-23 08:14
The docker-compose file looks fine. 

I can reproduce the behaviour with multiple song urls / searchqueries / playlist urls. Something is off. In the best case this is resolved by updating the used yt-dlp executable in the docker image, as I just recognized that it's quite outdated.

I'll test it out and open a PR :thinking:

**Comment by jontze** [comment] 2023-02-23 09:22
I could verify that this is related to the yt-dlp version in the current docker image on main.

As a quick fix I can offer you two workarounds until I published a fix for this:
1. Build the docker image yourself from source again, in this case you should get the latest yt-dlp version
2. Exec into your running docker container and run the following command `yt-dlp -U` - this will update the version in the image manually

**Comment by GolDNenex** [comment] 2023-02-23 12:21
Indeed, updating yt-dlp  also fix the issue on my side.

```
$ docker exec -it cadency_rs yt-dlp -U
Latest version: 2023.02.17, Current version: 2023.01.06
Current Build Hash 3b2d1bd378e08570b0fb5bee000cd6968563c4f47527197a5c57463bae8cb2ac
Updating to version 2023.02.17 ...
Updated yt-dlp to version 2023.02.17
```
Thank you very much for your help and your hard work:+1:

**Comment by jontze** [comment] 2023-02-23 12:45
Your welcome! I'll keep this open until I found an approach that prevents issues like this in the future or make it at least less likely. I'm currently thinking about an auto-updater for yt-dlp, but not set in stone yet :thinking:

**Comment by GolDNenex** [comment] 2023-02-23 13:09
Running `yt-dlp -U` when the bot start could be a good way of doing it.

**Comment by TeaDrinkingProgrammer** [comment] 2023-02-23 14:28
> Your welcome! I'll keep this open until I found an approach that prevents issues like this in the future or make it at least less likely. I'm currently thinking about an auto-updater for yt-dlp, but not set in stone yet 🤔

I have been following this, and I have an idea: auto deploying the docker image every once in a while (E.G every month). This updates both FFMPEG and yt-dlp as these are pulled from their respective repos. This could be used as an oppertunity to make both arm64 and amd64 builds of Cadency as well.

**Comment by jontze** [comment] 2023-02-25 12:59
You can now pull the latest `main` / `latest` / `0.3`  tag or just update to `0.3.2` and the play command should work again.

Thanks for reporting and participating!

**Closed by jontze** 2023-02-25 12:59 UTC
Labels: bug
